version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  colored:
    (): woninet.utilities.logger.ColorFormatter
    format: "%(asctime)s [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  file:
    class: logging.FileHandler
    filename: PLACEHOLDER.txt
    formatter: default
    level: INFO

  console:
    class: logging.StreamHandler
    formatter: colored
    level: INFO

loggers:
  uvicorn:
    handlers: [file, console]
    level: INFO
    propagate: False

  uvicorn.error:
    handlers: [file, console]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [file, console]
    level: INFO
    propagate: False

  core:
    handlers: [file, console]
    level: ERROR
    propagate: False

root:
  handlers: [console]
  level: INFO
